project:
  type: website
  render:
    - "*.qmd"
    - "!wip/"

website:
  title: "Oklahoma Policy Institute"
  favicon: www/favicon.gif
  search: false
  navbar:
    background: "#2f507f"
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: About
      - text: Reports
        menu:
          - href: report-1/index.qmd
            text: "Report 1"
          - href: report-2/index.qmd
            text: "Report 2"

format:
  okpolicy-website-template-html:
    css:
      - draft.css
    include-before-body:
      - draft-banner.html
  html:
    toc: true
